site_name: Documentación
site_description: Mi documentación de java
site_author: Yo

theme: readthedocs
nav:
  - Inicio: index.md
  - Introduccion a la Programacion:
    - Introducción: IntroduccionProgramacion/Introduccion.md
  - Empezando con Java:
    - El Inicio: FundamentosJava/Empezando.md
    - Variables y tipos de datos: FundamentosJava/VariablesYDataTypes.md
    - Casting de Java: FundamentosJava/Casting.md
    - Operadores: FundamentosJava/Operadores.md